name: Java CI

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build dependency-check
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Build with Maven
        run: mvn -s settings.xml verify -DreleaseTesting --no-transfer-progress --batch-mode
      - name: Archive IT test logs
        uses: actions/upload-artifact@v2
        with:
          name: it-test-logs
          retention-days: 7
          path: |
            maven/target/it/1551-verify-dependency-managemen/build.log
            maven/target/it/740-aggregate/build.log
            maven/target/it/617-hierarchical-cross-deps/build.log
            maven/target/it/618-aggregator-purge/build.log
            maven/target/it/618-aggregator-update-only/build.log
            maven/target/it/629-jackson-dataformat/build.log
            maven/target/it/690-threadsafety/build.log
            maven/target/it/710-pom-parse-error/build.log
            maven/target/it/729-system-scope-resolved/build.log
            maven/target/it/729-system-scope-skipped/build.log
            maven/target/it/730-multiple-suppression-files/build.log
            maven/target/it/730-multiple-suppression-files-configs/build.log
            maven/target/it/815-broken-suppression-aggregate/build.log
            maven/target/it/846-site-plugin/build.log
            maven/target/it/false-positives/build.log
            maven/target/it/1512-transitive-test/build.log
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          retention-days: 7
          path: |
            utils/target/jacoco-results/jacoco.xml
            core/target/jacoco-results/jacoco.xml
            maven/target/jacoco-results/jacoco.xml
            ant/target/jacoco-results/jacoco.xml
            cli/target/jacoco-results/jacoco.xml
            utils/target/jacoco-    results/**/*.html
            core/target/jacoco-results/**/*.html
            maven/target/jacoco-results/**/*.html
            ant/target/jacoco-results/**/*.html
            cli/target/jacoco-results/**/*.html
  
  publish_coverage:
    name: publish code coverage reports  
    runs-on: ubuntu-latest 
    needs: build
    steps:
      - name: Download coverage reports
        if: github.ref == 'refs/heads/main'
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
      - name: Run codacy-coverage-reporter
        if: github.ref == 'refs/heads/main'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: utils/target/jacoco-results/jacoco.xml,core/target/jacoco-results/jacoco.xml,maven/target/jacoco-results/jacoco.xml,ant/target/jacoco-results/jacoco.xml,cli/target/jacoco-results/jacoco.xml
