on:
  push:
    branches:
      - main
#    tags:
#      - 'v*'

name: Create Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/
          key: mvn-repo
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Build with Maven
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: mvn -s settings.xml -Prelease clean package verify source:jar javadoc:jar site site:stage gpg:sign deploy -DreleaseTesting --no-transfer-progress --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} 
      - name: Archive Release
        uses: actions/upload-artifact@v2
        with:
          name: archive-release
          retention-days: 7
          path: |
            maven/target/*.asc
            maven/target/*.jar
            maven/target/*.pom
            ant/target/*.asc
            ant/target/*.zip
            ant/taget/*.jar
            ant/target/*.pom
            cli/target/*.asc
            cli/target/*.zip
            core/target/*.asc
            core/target/*.jar
            core/target/*.pom
            utils/target/*.asc
            utils/target/*.jar
            utils/target/*.pom
            archetype/target/*.asc
            archetype/target/*.jar
            archetype/target/*.pom
            target/*.asc
            target/*.pom
      - name: Archive Site
        uses: actions/upload-artifact@v2
        with:
          name: archive-site
          retention-days: 7
          path: target/staging/
#  release:
#    name: Publish Release
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
#          draft: false
#          prerelease: false
